version: "3.8"

volumes:
  nextcloud-data:
  pihole-data:
  checkmk-data:
  wireguard-data:

services:

  # ----------------------------
  # Traefik Reverse Proxy
  # ----------------------------
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.insecure=true" # Optional: Traefik dashboard
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-data:/traefik"
    restart: unless-stopped

  # ----------------------------
  # Nextcloud
  # ----------------------------
  nextcloud:
    build: ./services/nextcloud
    container_name: nextcloud
    depends_on:
      - db
    environment:
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
    volumes:
      - nextcloud-data:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_DOMAIN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
    restart: unless-stopped

  db:
    image: mariadb:10.6
    container_name: nextcloud-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - nextcloud-data:/var/lib/mysql
    restart: unless-stopped

  # ----------------------------
  # Pi-hole
  # ----------------------------
  pihole:
    build: ./services/pihole
    container_name: pihole
    environment:
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
    volumes:
      - pihole-data:/etc/pihole
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`${PIHOLE_DOMAIN}`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
    restart: unless-stopped

  # ----------------------------
  # Checkmk
  # ----------------------------
  checkmk:
    build: ./services/checkmk
    container_name: checkmk
    environment:
      CMK_ADMIN_PASSWORD: ${CHECKMK_PASSWORD}
    volumes:
      - checkmk-data:/omd/sites
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.checkmk.rule=Host(`${CHECKMK_DOMAIN}`)"
      - "traefik.http.routers.checkmk.entrypoints=websecure"
    restart: unless-stopped

  # ----------------------------
  # WireGuard VPN
  # ----------------------------
  wireguard:
    build: ./services/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      WG_PORT: 51820
      WG_HOST: ${WIREGUARD_DOMAIN}
      WG_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      WG_PEERS: ${WIREGUARD_PEERS}
    ports:
      - "51820:51820/udp"
    volumes:
      - wireguard-data:/etc/wireguard
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
