version: "3.8"

services:
  caddy:
    image: caddy:2
    container_name: dkljajogithubio-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DUCKDNS_DOMAIN=dkljajo.duckdns.org   # replace with your actual DuckDNS domain
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - nextcloud

  nextcloud:
    image: nextcloud:32-apache
    container_name: dkljajogithubio-nextcloud
    restart: unless-stopped
    environment:
      - MYSQL_PASSWORD=NextcloudDBPass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    depends_on:
      - db
    volumes:
      - nextcloud_data:/var/www/html

  db:
    image: mariadb:latest
    container_name: dkljajogithubio-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=NextcloudDBPass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  caddy_data:
  caddy_config:
  nextcloud_data:
  db_data:
