services:
  caddy:
    image: caddy:2
    container_name: dkljajogithubio-caddy-1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
    depends_on:
      - nextcloud
      - pihole
      - checkmk

volumes:
  caddy_data:
  caddy_config:
