version: "3.9"

services:

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik/Caddyfile:/etc/caddy/Caddyfile
      - ./traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    depends_on:
      - db
    labels:
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.dkljajo.github.io`)"
      
  db:
    image: mariadb:latest
    container_name: nextcloud-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=password

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    environment:
      - WEBPASSWORD=secret
    labels:
      - "traefik.http.routers.pihole.rule=Host(`pihole.dkljajo.github.io`)"
      
  checkmk:
    image: checkmk/check-mk-raw:2.2.0-latest
    container_name: checkmk
    restart: always
    labels:
      - "traefik.http.routers.checkmk.rule=Host(`checkmk.dkljajo.github.io`)"
      
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    labels:
      - "traefik.http.routers.wireguard.rule=Host(`wg.dkljajo.github.io`)"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
